#!/bin/sh

export PYTHONPATH=./tools/lib/:..:$PYTHONPATH

if git rev-parse --verify HEAD >/dev/null 2>&1
then
  against=HEAD
else
  against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

py_flag=0

pyfiles=$(git diff-index --name-only --diff-filter=ACMR ${against} -- \
  | grep '.py$')

if test -z "$pyfiles"
then
  echo "no diff python files for flake8"
elif which pylint >/dev/null
then
  for file in $pyfiles
  do
    flake8 $file || py_flag=1
  done
else
  echo "pip install -r pip-require.txt plz"
fi

all_flag=`expr $py_flag`
exit $all_flag
